function [TLEs] = processBulkTLEs(par, file)
% PROCESSBULKTLES 
%
% Inputs:
%   par = parameters structure as generated by processParam
%   file = path to file in data folder
%
% Ouputs:
%   TLEs = list of TLEs
%       .elem = orbital elements
%       .ECI = ECI position corresponding to TLE
% 

% no fsolve ouput
par.DEBUG = 0;

%% Opening file
all_lines = char(splitlines(extractFileText(['data/', file, '.txt'])));
nb_lines = size(all_lines, 1);


%% Parsing TLEs
TLEs = [];

for l = 1:3:nb_lines-3+1
    % extracting lines
    TLE.L0 = all_lines(l,   3:end);
    TLE.L1 = all_lines(l+1, 1:end);
    TLE.L2 = all_lines(l+2, 1:end);
    
    % processing each TLE
    [TLE.processed, TLE.elem, TLE.ECI] = processTLE(par, TLE.L0, TLE.L1, TLE.L2);
    
    % adding TLE to list of TLEs
    TLEs = [TLEs; TLE];
end

end