function parOUT = processParam(parIN)
% PROCESSPARAM processes parameters
% 
% Inputs:
%   parIN = user parameters structure generated by 'parameters.m'
% 
% Outputs:
%   parOUT = 
%       processed parameters that can be used for the simulation. The goal
%       is that no parameter should be hardcoded
% 

% User parameters
par = parIN; % copy user parameters

% Add physical constants and data (used later in the function)
par.pdata = planetaryData();

% Create derived variables
par.tspan = linspace(0, par.T_END, par.N_STEP);
[par.TLE.processed, par.Orb_elem0, par.ECI0] = processTLE(par);


% Dev
if par.DEBUG
    par.displ_stats = 'on';
else
    par.displ_stats = 'off';
end

parOUT = par;

end