function parOUT = processParam(parIN)
% PROCESSPARAM processes parameters
% 
% Inputs:
%   parIN = user parameters structure generated by 'parameters.m'
% 
% Outputs:
%   parOUT = 
%       processed parameters that can be used for the simulation. The goal
%       is that no parameter should be hardcoded
% 

% User parameters
parOUT = parIN; % copy user parameters

% Create derived variables
parOUT.tspan = linspace(0, parIN.N_STEP, parIN.T_END);
[parOUT.TLE parOUT.states] = processTLE(parIN.TLE);

% Add physical constants and data
parOUT.pdata = planetaryData();

end